# Setup
title:               Development Blog
tagline:             'SooKim1110'
description:         'Sharing my thoughts and what I learned.'
url:                 https://SooKim1110.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Jisoo Kim
  url:               https://twitter.com/
  email:             ohjskim@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
